baseURL = "http://www.prfrankild.dk/sem3/design_systems/"
languageCode = "en-us"
title = "Hugo design systems"
theme = "hugo_design_systems"
publishDir = "public"

[taxonomies]
  tag = "tags"
  category = "categories"
  mood = "moods"

[Params]
 author = "pete414r"
 facebook = "peter414r"
 instagram = "peter414r"
 github = "peter414r"
 email = "pete414r@stud.kea.dk"
 copyright = true

[[menu.main]]
    name = "Home"
    title = "home section"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Dokumentation"
    title = "dokumentation section"
    weight = 2
    identifier = "dokumentation"
    url = "/dokumentation/"

[[menu.main]]
    name = "Datavisualisering"
    title = "datavisualisering section"
    weight = 3
    identifier = "datavisualisering"
    url = "/datavisualisering/"
    [[menu.main]]

  name = "Blog"
  title = "Blog"
  weight = 4
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
      name = "Om"
      title = "om section"
      weight = 5
      identifier = "om"
      url = "/om"
