baseURL = "http://example.org/"
languageCode = "en-us"
title = "Prf doc statisk site"
theme = "ga-hugo-theme"
[taxonomies]
tag = "tags"
category = "categories"
mood = "moods"
[[menu.main]]
name                   = "Forside"
weight                 = -130
identifier             = "forside"
url                    = "/forside/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Om"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Kontkt"
weight                 = -100
identifier             = "code"
url                    = "/code/"

[[menu.main]]
name                   = "Portfolio"
weight                 = -100
identifier             = "portfolio"
url                    = "/portfolio/"
