title = "Design systems"
baseURL = "http://example.org/"

languageCode = "en-us"
theme = "design_systems"
publishDir = "public"

[[menu.main]]
    name = "Home"
    title = "home section"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Dokumentation"
    title = "dokumentation section"
    weight = 2
    identifier = "dokumentation"
    url = "/dokumentation/"

[[menu.main]]
    name = "Om"
    title = "om section"
    weight = 3
    identifier = "om"
    url = "/om"

[[menu.main]]
    name = "Datavisualisering"
    title = "datavisualisering section"
    weight = 4
    identifier = "datavisualisering"
    url = "/datavisualisering/"
